app:
  telegram-token: ${TELEGRAM_TOKEN}

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  config:
    import: optional:file:.env[.properties]

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
