app:
  telegram-token: ${TELEGRAM_TOKEN}
  use-queue: true
  scrapper-client:
    api: http://localhost:8080
    retry:
      strategy: fixed
      max-attempts: 3
      backoff: 2000
      codes: 429, 503, 504
  link-sources:
    github:
      domain: github.com
      regex:
        repository: /(?<owner>[\w-\.]+)/(?<repo>[\w-\.]+)
        branch: /(?<owner>[\w-\.]+)/(?<repo>[\w-\.]+)/tree/(?<branch>[\w-\./]+)
        pull-request: /(?<owner>[\w-\.]+)/(?<repo>[\w-\.]+)/pull/(?<num>\d+)
        issue: /(?<owner>[\w-\.]+)/(?<repo>[\w-\.]+)/issues/(?<num>\d+)
    stackoverflow:
      domain: stackoverflow.com
      regex:
        question: /(?:questions|q)/(?<id>[\d]+)[/\w-\d]*
  kafka-topics:
    link-update:
      name: link-update
      partitions: 1
      replicas: 3
    link-update-dlq:
      name: link-update-dlq
      partitions: 1
      replicas: 1
  kafka-retry:
    max-attempts: 3
    backoff: 2000
    max-backoff: 10000
    multiplier: 2

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  config:
    import: optional:file:.env[.properties]
  messages:
    basename: messages
    encoding: UTF-8
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s
    jcache:
      provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
  kafka:
    bootstrap-servers: localhost:29091,localhost:29092,localhost:29093
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 100
    producer:
      client-id: ${spring.application.name}

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
    disable-swagger-default-url: true
    tags-sorter: alpha
    operations-sorter: method
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: (/updates.*)
      http-response-body: "{\"description\":\"429 TOO_MANY_REQUESTS\",\"code\":\"RATE_LIMIT\",\"exceptionName\":\"ApiException\",\"exceptionMessage\":\"Too Many Requests\",\"stacktrace\":[]}"
      rate-limits:
        - cache-key: "getRemoteAddr()"
          bandwidths:
            - capacity: 50
              time: 1
              unit: seconds
