/*
 * This file is generated by jOOQ.
 */
package edu.java.model.jooq;


import javax.annotation.processing.Generated;

import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sequences {

    /**
     * The sequence <code>CHATS_ID_SEQ</code>
     */
    public static final Sequence<Long> CHATS_ID_SEQ = Internal.createSequence("CHATS_ID_SEQ", DefaultSchema.DEFAULT_SCHEMA, SQLDataType.BIGINT, null, null, null, null, false, null);

    /**
     * The sequence <code>LINKS_ID_SEQ</code>
     */
    public static final Sequence<Long> LINKS_ID_SEQ = Internal.createSequence("LINKS_ID_SEQ", DefaultSchema.DEFAULT_SCHEMA, SQLDataType.BIGINT, null, null, null, null, false, null);
}
